<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_68321d2564253',
	'title' => 'Product: QA Kit',
	'fields' => array(
		array(
			'key' => 'field_684d2b90093a8',
			'label' => 'Configuration',
			'name' => 'configuration',
			'aria-label' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'relevanssi_exclude' => 0,
			'choices' => array(
				'qa' => 'Quick Attach',
			),
			'default_value' => array(
			),
			'return_format' => 'value',
			'allow_custom' => 0,
			'allow_in_bindings' => 0,
			'layout' => 'horizontal',
			'toggle' => 0,
			'save_custom' => 0,
			'custom_choice_button_text' => 'Add new choice',
		),
		array(
			'key' => 'field_684d2bed093a9',
			'label' => 'Quick Attach',
			'name' => 'quick_attach',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_684d2b90093a8',
						'operator' => '==',
						'value' => 'qa',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'relevanssi_exclude' => 0,
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_684d2bfe093aa',
					'label' => 'Bucket Plate',
					'name' => 'bucket_plate',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'post_type' => array(
						0 => 'product',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_684d2c19093ab',
					'label' => 'Sizes',
					'name' => 'sizes',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'layout' => 'block',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Size',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_684d2c24093ac',
							'label' => 'Width',
							'name' => 'width',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'relevanssi_exclude' => 0,
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_684d2c19093ab',
						),
						array(
							'key' => 'field_684d2c37093ad',
							'label' => 'Buckets',
							'name' => 'buckets',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'relevanssi_exclude' => 0,
							'layout' => 'block',
							'pagination' => 0,
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Bucket',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_684d2c46093ae',
									'label' => 'Bucket',
									'name' => 'bucket',
									'aria-label' => '',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'relevanssi_exclude' => 0,
									'post_type' => array(
										0 => 'product',
									),
									'post_status' => '',
									'taxonomy' => '',
									'return_format' => 'id',
									'multiple' => 0,
									'allow_null' => 0,
									'allow_in_bindings' => 0,
									'bidirectional' => 0,
									'ui' => 1,
									'bidirectional_target' => array(
									),
									'parent_repeater' => 'field_684d2c37093ad',
								),
								array(
									'key' => 'field_684d2c67093af',
									'label' => 'Accessories',
									'name' => 'accessories',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'relevanssi_exclude' => 0,
									'layout' => 'block',
									'pagination' => 0,
									'min' => 0,
									'max' => 0,
									'collapsed' => '',
									'button_label' => 'Add Accessory',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_684d2c8d093b0',
											'label' => 'Accessory',
											'name' => 'accessory',
											'aria-label' => '',
											'type' => 'post_object',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'relevanssi_exclude' => 0,
											'post_type' => array(
												0 => 'product',
											),
											'post_status' => '',
											'taxonomy' => '',
											'return_format' => 'id',
											'multiple' => 0,
											'allow_null' => 0,
											'allow_in_bindings' => 0,
											'bidirectional' => 0,
											'ui' => 1,
											'bidirectional_target' => array(
											),
											'parent_repeater' => 'field_684d2c67093af',
										),
									),
									'parent_repeater' => 'field_684d2c37093ad',
								),
							),
							'parent_repeater' => 'field_684d2c19093ab',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );
} );